### ISSUE TITLE
NoClassDefFoundError: FilenameUtils (commons.io)

### ISSUE THREAD

**Issue by minhh2792** [CortezRomeo/TaiXiu#3]
![image](https://user-images.githubusercontent.com/63439671/196241093-430ca7f7-531d-47ea-964a-2b362946f9bb.png)

Purpur 1.17.1
Java Zulu 17

**Comment by CortezRomeo** [comment]
Tải bản mới nhất coi còn bị không ông.

**Comment by minhh2792** [comment]
Alr
