### ISSUE TITLE
Offline player không nhận được tiền sau khi cược thắng.

### ISSUE THREAD

**Issue by kolderz** [CortezRomeo/TaiXiu#6]
Sau khi cược mà thoát thì lúc cược đúng ko nhận được tiền.

`ERROR]: java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.isOnline()" because the return value of "org.bukkit.Bukkit.getPlayer(String)" is null`

**Comment by CortezRomeo** [comment]
Đã fix trong bản mới nhất
